import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="top" className="min-h-screen bg-gradient-to-br from-[#020610] to-[#111724] flex justify-center items-center">
      <main>{children}</main>
    </div>
  );
}