import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/LandingPage/Header";
import Footer from "@/components/LandingPage/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="top" className="min-h-screen bg-gradient-to-br from-[#020610] to-[#111724]">
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
}